Add the missing job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -76,6 +76,232 @@ parameters:
     type: string
     default: 'jahia/module-manager'
 
+jobs:
+  integration_testsjava:
+    <<: *workdir
+    machine: true
+    # Available types: medium, large, xlarge, 2xlarge https://circleci.com/docs/2.0/configuration-reference/#machine-executor-linux
+    resource_class: xlarge
+    parameters:
+      TESTRAIL_MILESTONE:
+        type: string
+        default: Default
+      JAHIA_IMAGE:
+        type: string
+      MANIFEST:
+        type: string
+      JAHIA_URL:
+        type: string
+        default: http://jahia:8080
+      JAHIA_USERNAME:
+        type: string
+        default: root
+      JAHIA_PASSWORD:
+        type: string
+        default: root
+      JAHIA_USERNAME_TOOLS:
+        type: string
+        default: jahia
+      JAHIA_PASSWORD_TOOLS:
+        type: string
+        default: password
+      # Why this is not a boolean, see: https://discuss.circleci.com/t/run-job-within-workflow-conditionally/34125/2
+      SKIP_TESTRAIL:
+        type: string
+        default: ""
+      SKIP_ARTIFACTS:
+        type: boolean
+        default: true
+      RUN_TESTSIMAGE:
+        type: string
+        default: << pipeline.parameters.TESTSJAVA_IMAGE >>:latest
+      BUILD_TESTSIMAGE:
+        type: boolean
+        default: false
+    steps:
+      - *attach-workspace
+      - restore_cache:
+          keys:
+            - v1-dependencies-{{ checksum "pom.xml" }}
+            # fallback to using the latest cache if no exact match is found
+            - v1-dependencies-
+      - run:
+          name: Prepare artifacts
+            # This command copy the source subfolders and the various build artifacts into the /module-manager-test-docker/ folder
+            # The POM files will be used by the Maven test call
+            # The artifacts will be used by jahia-cli to provision Jahia for testing
+          command: |
+            if [ ! -d << pipeline.parameters.TESTSJAVA_PATH >>artifacts ]; then
+              mkdir -p << pipeline.parameters.TESTSJAVA_PATH >>artifacts
+              mkdir << pipeline.parameters.TESTSJAVA_PATH >>artifacts/reports
+            fi
+            cp pom.xml << pipeline.parameters.TESTSJAVA_PATH >>pom.xml
+            if [ ! -d << pipeline.parameters.TESTSJAVA_PATH >>module-manager ]; then
+                mkdir << pipeline.parameters.TESTSJAVA_PATH >>module-manager
+            fi
+            if [ ! -d << pipeline.parameters.TESTSJAVA_PATH >>module-manager-test ]; then
+                mkdir << pipeline.parameters.TESTSJAVA_PATH >>module-manager-test
+            fi
+            cp -R /home/circleci/source/module-manager/* << pipeline.parameters.TESTSJAVA_PATH >>module-manager/
+            cp -R /home/circleci/source/module-manager-test/* << pipeline.parameters.TESTSJAVA_PATH >>module-manager-test/
+            if [ << parameters.SKIP_ARTIFACTS >> == false ]; then
+              sudo cp /home/circleci/source/module-manager/target/*.jar << pipeline.parameters.TESTSJAVA_PATH >>artifacts/
+              sudo cp << pipeline.parameters.TESTSJAVA_PATH >>artifacts/module-manager*SNAPSHOT.jar << pipeline.parameters.TESTSJAVA_PATH >>artifacts/module-manager-SNAPSHOT.jar
+              sudo cp /home/circleci/source/module-manager-test/target/*.jar << pipeline.parameters.TESTSJAVA_PATH >>artifacts/
+              sudo cp << pipeline.parameters.TESTSJAVA_PATH >>artifacts/module-manager-test*SNAPSHOT.jar << pipeline.parameters.TESTSJAVA_PATH >>artifacts/module-manager-test-SNAPSHOT.jar
+            fi
+      - run:
+          name: Docker login
+          # This is needed to fetch private docker images (such as Jahia snapshot)
+          command: |
+            echo "$DOCKERHUB_LOGIN"
+            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_LOGIN" --password-stdin
+      - run:
+          name: Spin-up dockerized jahia
+          # At that point we're only sprinning up Jahia and its runtime dependencies,
+          # We are not starting the tests yet since we first want to build the test container (or run from a previously built container)
+          # Copying the main folder content into the tests folder is there to have
+          #   the POM files usable by the tests executed by Maven at this level
+          # Checking the presence of the .env file is there because it's needed by the tests, but to not break ci/cd if variables
+          #   are added to the compose file but not to the environment variables in circleci config.yml
+          command: |
+            set -e
+            cd << pipeline.parameters.TESTSJAVA_PATH >>
+            if [[ ! -e .env ]]; then
+              mv .env.example .env
+            fi
+            docker-compose -f docker-compose.yml up -d jahia
+          no_output_timeout: 2h
+          environment:
+            MANIFEST: << parameters.MANIFEST >>
+            JAHIA_IMAGE: << parameters.JAHIA_IMAGE >>
+            TESTSJAVA_IMAGE: << parameters.RUN_TESTSIMAGE >>
+            JAHIA_URL: << parameters.JAHIA_URL >>
+            JAHIA_HOST: jahia
+            JAHIA_PORT: 8080
+            TEST_URL: http://jahia:8080/
+            JAHIA_USERNAME: root
+            JAHIA_PASSWORD: root
+      - run:
+          # We want to build the test image from scratch with any code change (since that code change could be in the tests themselves)
+          name: Build << pipeline.parameters.TESTSJAVA_IMAGE >> image
+          command: |
+            if [ << parameters.BUILD_TESTSIMAGE >> == true ]; then
+              cd << pipeline.parameters.TESTSJAVA_PATH >>
+              docker build -t << pipeline.parameters.TESTSJAVA_IMAGE >> .
+              docker save -o tests_image.tar << pipeline.parameters.TESTSJAVA_IMAGE >>
+            fi
+      - run:
+          name: Execute tests
+          # Running the tests, note that the reports are copied at the end of execution
+          # We don't need (nor want) this actual step to fail
+          # Failure is determined by counting the number of failed tests in the output report
+          # Note: the timeout env vars are added to address this: https://github.com/docker/compose/issues/3927
+          command: |
+            set -e
+            cd << pipeline.parameters.TESTSJAVA_PATH >>
+            export DOCKER_CLIENT_TIMEOUT=120
+            export COMPOSE_HTTP_TIMEOUT=120
+            docker-compose -f docker-compose.yml up maven
+            docker cp e2e-tests:/tmp/results ./artifacts/results
+          no_output_timeout: 2h
+          environment:
+            MANIFEST: << parameters.MANIFEST >>
+            JAHIA_IMAGE: << parameters.JAHIA_IMAGE >>
+            TESTSJAVA_IMAGE: << parameters.RUN_TESTSIMAGE >>
+            JAHIA_URL: << parameters.JAHIA_URL >>
+            JAHIA_HOST: jahia
+            JAHIA_PORT: 8080
+            TEST_URL: http://jahia:8080/
+            JAHIA_USERNAME: root
+            JAHIA_PASSWORD: root
+      - run:
+          name: Export jahia logs
+          when: always
+          command: |
+            set -e
+            cd << pipeline.parameters.TESTSJAVA_PATH >>
+            docker logs jahia > ./artifacts/results/jahia.log
+            docker logs e2e-tests > ./artifacts/results/tests.log
+      # This fetches data about the running Jahia (jahia versions, module version, ...)
+      # This is useful as an artifact but also used by the slack and zencrepes reporters to
+      # Populate the data they're sending
+      - run:
+          name: Fetch module dependencies
+          when: always
+          command: |
+            set +e
+            cd << pipeline.parameters.TESTSJAVA_PATH >>
+            export NVM_DIR="/opt/circleci/.nvm"
+            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+            nvm install v12
+            nvm alias default v12
+            npm install -g jahia-reporter
+            echo "Fetching modules"
+            jahia-reporter utils:modules \
+              --moduleId="<< pipeline.parameters.MODULE_ID >>" \
+              --dependencies="module-manager" \
+              --filepath="artifacts/results/installed-jahia-modules.json"
+      # This is not needed since cypress is going to terminat on failure with exit code 1
+      - run:
+          name: Analyze Test results
+          when: always
+          # This looks at the report and fail the job if one of the test has failed
+          command: |
+            cd << pipeline.parameters.TESTSJAVA_PATH >>
+            if [[ ! -e ./artifacts/results/test_success ]]; then
+              echo "More than one failure found, sending exit signal"
+              exit 1
+            fi
+      - store_test_results:
+          path: << pipeline.parameters.TESTSJAVA_PATH >>artifacts/results/reports
+      - store_artifacts:
+          path: << pipeline.parameters.TESTSJAVA_PATH >>artifacts/results
+      # Once all is executed, results are submitted to external platforms
+      # Testrail report and Slack (failure only) notifications are sent during scheduled executions or merged into the main branch
+      # jahia-reporter can be executed either in docker or through node directly.
+      - run:
+          name: Publish results to testrail
+          when: always
+          command: |
+            set +e
+            if [ "<< parameters.SKIP_TESTRAIL >>" != "true" ] || [ "$CIRCLE_BRANCH" = "<< pipeline.parameters.PRIMARY_RELEASE_BRANCH >>" ]; then
+              cd << pipeline.parameters.TESTSJAVA_PATH >>
+              export NVM_DIR="/opt/circleci/.nvm"
+              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
+              nvm alias default v12
+              echo "Sending slack message"
+              jahia-reporter slack \
+                --channelId=$SLACK_CHANNEL_ID_QA_NOTIFICATIONS \
+                --channelAllId=$SLACK_CHANNEL_ID_QA_NOTIFICATIONS_ALL \
+                --token=$SLACK_CLIENT_TOKEN \
+                --skipSuccessful \
+                --sourcePath="artifacts/results/reports" \
+                --sourceType="xml" \
+                --moduleFilepath="artifacts/results/installed-jahia-modules.json" \
+                --msgAuthor="CircleCI ($CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME)" \
+                --runUrl=$CIRCLE_BUILD_URL
+              echo "Sending Zencrepes matrix"
+              jahia-reporter zencrepes \
+                --webhook="https://zencrepes.jahia.com/zqueue/testing/webhook" \
+                --webhookSecret=$ZENCREPES_WEBHOOK_SECRET \
+                --sourcePath="artifacts/results/reports" \
+                --sourceType="xml" \
+                --moduleFilepath="artifacts/results/installed-jahia-modules.json" \
+                --name="<< pipeline.parameters.MODULE_ID >>" \
+                --runUrl=$CIRCLE_BUILD_URL
+              echo "Sending testrail report"
+              jahia-reporter testrail \
+                --testrailUsername=$TESTRAIL_USERNAME \
+                --testrailPassword=$TESTRAIL_PASSWORD \
+                --sourcePath="artifacts/results/reports" \
+                --sourceType="xml" \
+                --projectName="<< pipeline.parameters.TESTRAIL_PROJECTNAME >>" \
+                --milestone="<< parameters.TESTRAIL_MILESTONE >>" \
+                --defaultRunDescription="This test was executed on circleci, $CIRCLE_BUILD_URL"
+            fi
+      - *persist-workspace
+
 workflows:
   version: 2
   # On code change is executed each time new code is pushed to a branch
@@ -116,7 +342,7 @@ workflows:
               only:
                 - << pipeline.parameters.PRIMARY_RELEASE_BRANCH >>
       # Verifies that the new code works with the latest released version of Jahia
-      - jahia-modules-orb/integration_testsjava:
+      - integration_testsjava:
           name: 'Int. Tests - Jahia Latest - Built modules'
           requires:
             - jahia-modules-orb/build
@@ -262,7 +488,7 @@ workflows:
                 - << pipeline.parameters.PRIMARY_RELEASE_BRANCH >>
     jobs:
       - jahia-modules-orb/initialize
-      - jahia-modules-orb/integration_testsjava:
+      - integration_testsjava:
           JAHIA_IMAGE: jahia/jahia-ee-dev:8-SNAPSHOT
           RUN_TESTSIMAGE: << pipeline.parameters.TESTSJAVA_IMAGE >>:latest
           MANIFEST: warmup-manifest-snapshot.yml
@@ -275,7 +501,7 @@ workflows:
           context: QA_ENVIRONMENT
           requires:
             - jahia-modules-orb/initialize
-      - jahia-modules-orb/integration_testsjava:
+      - integration_testsjava:
           JAHIA_IMAGE: jahia/jahia-ee:8
           RUN_TESTSIMAGE: << pipeline.parameters.TESTSJAVA_IMAGE >>:latest
           MANIFEST: warmup-manifest-release.yml
